/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppChallengesIndexRouteImport } from './routes/_app/challenges/index'
import { Route as AdminSubmissionsSubmissionIdRouteImport } from './routes/admin/submissions_.$submissionId'
import { Route as AdminSubmissionsChar123submissionIdChar125_modalRouteImport } from './routes/admin/submissions.{$submissionId}_modal'
import { Route as AppChallengesChallengeIdRouteRouteImport } from './routes/_app/challenges/$challengeId/route'
import { Route as AppChallengesChallengeIdSubmitRouteImport } from './routes/_app/challenges/$challengeId/submit'
import { Route as AppChallengesChallengeIdOverviewRouteImport } from './routes/_app/challenges/$challengeId/overview'
import { Route as AppChallengesChallengeIdLeaderboardRouteImport } from './routes/_app/challenges/$challengeId/leaderboard'
import { Route as AppChallengesChallengeIdFilesRouteImport } from './routes/_app/challenges/$challengeId/files'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppChallengesIndexRoute = AppChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminSubmissionsSubmissionIdRoute =
  AdminSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions_/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSubmissionsChar123submissionIdChar125_modalRoute =
  AdminSubmissionsChar123submissionIdChar125_modalRouteImport.update({
    id: '/{$submissionId}_modal',
    path: '/{$submissionId}_modal',
    getParentRoute: () => AdminSubmissionsRoute,
  } as any)
const AppChallengesChallengeIdRouteRoute =
  AppChallengesChallengeIdRouteRouteImport.update({
    id: '/challenges/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppChallengesChallengeIdSubmitRoute =
  AppChallengesChallengeIdSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AppChallengesChallengeIdRouteRoute,
  } as any)
const AppChallengesChallengeIdOverviewRoute =
  AppChallengesChallengeIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppChallengesChallengeIdRouteRoute,
  } as any)
const AppChallengesChallengeIdLeaderboardRoute =
  AppChallengesChallengeIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AppChallengesChallengeIdRouteRoute,
  } as any)
const AppChallengesChallengeIdFilesRoute =
  AppChallengesChallengeIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppChallengesChallengeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRouteWithChildren
  '/challenges/$challengeId': typeof AppChallengesChallengeIdRouteRouteWithChildren
  '/admin/submissions/{$submissionId}_modal': typeof AdminSubmissionsChar123submissionIdChar125_modalRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/challenges/$challengeId/files': typeof AppChallengesChallengeIdFilesRoute
  '/challenges/$challengeId/leaderboard': typeof AppChallengesChallengeIdLeaderboardRoute
  '/challenges/$challengeId/overview': typeof AppChallengesChallengeIdOverviewRoute
  '/challenges/$challengeId/submit': typeof AppChallengesChallengeIdSubmitRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRouteWithChildren
  '/challenges/$challengeId': typeof AppChallengesChallengeIdRouteRouteWithChildren
  '/admin/submissions/{$submissionId}_modal': typeof AdminSubmissionsChar123submissionIdChar125_modalRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/challenges/$challengeId/files': typeof AppChallengesChallengeIdFilesRoute
  '/challenges/$challengeId/leaderboard': typeof AppChallengesChallengeIdLeaderboardRoute
  '/challenges/$challengeId/overview': typeof AppChallengesChallengeIdOverviewRoute
  '/challenges/$challengeId/submit': typeof AppChallengesChallengeIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRouteWithChildren
  '/_app/challenges/$challengeId': typeof AppChallengesChallengeIdRouteRouteWithChildren
  '/admin/submissions/{$submissionId}_modal': typeof AdminSubmissionsChar123submissionIdChar125_modalRoute
  '/admin/submissions_/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/_app/challenges/': typeof AppChallengesIndexRoute
  '/_app/challenges/$challengeId/files': typeof AppChallengesChallengeIdFilesRoute
  '/_app/challenges/$challengeId/leaderboard': typeof AppChallengesChallengeIdLeaderboardRoute
  '/_app/challenges/$challengeId/overview': typeof AppChallengesChallengeIdOverviewRoute
  '/_app/challenges/$challengeId/submit': typeof AppChallengesChallengeIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/admin/submissions'
    | '/challenges/$challengeId'
    | '/admin/submissions/{$submissionId}_modal'
    | '/admin/submissions/$submissionId'
    | '/challenges'
    | '/challenges/$challengeId/files'
    | '/challenges/$challengeId/leaderboard'
    | '/challenges/$challengeId/overview'
    | '/challenges/$challengeId/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/admin/submissions'
    | '/challenges/$challengeId'
    | '/admin/submissions/{$submissionId}_modal'
    | '/admin/submissions/$submissionId'
    | '/challenges'
    | '/challenges/$challengeId/files'
    | '/challenges/$challengeId/leaderboard'
    | '/challenges/$challengeId/overview'
    | '/challenges/$challengeId/submit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/admin'
    | '/_auth/login'
    | '/admin/submissions'
    | '/_app/challenges/$challengeId'
    | '/admin/submissions/{$submissionId}_modal'
    | '/admin/submissions_/$submissionId'
    | '/_app/challenges/'
    | '/_app/challenges/$challengeId/files'
    | '/_app/challenges/$challengeId/leaderboard'
    | '/_app/challenges/$challengeId/overview'
    | '/_app/challenges/$challengeId/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/challenges/': {
      id: '/_app/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/submissions_/$submissionId': {
      id: '/admin/submissions_/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/admin/submissions/$submissionId'
      preLoaderRoute: typeof AdminSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions/{$submissionId}_modal': {
      id: '/admin/submissions/{$submissionId}_modal'
      path: '/{$submissionId}_modal'
      fullPath: '/admin/submissions/{$submissionId}_modal'
      preLoaderRoute: typeof AdminSubmissionsChar123submissionIdChar125_modalRouteImport
      parentRoute: typeof AdminSubmissionsRoute
    }
    '/_app/challenges/$challengeId': {
      id: '/_app/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof AppChallengesChallengeIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/challenges/$challengeId/submit': {
      id: '/_app/challenges/$challengeId/submit'
      path: '/submit'
      fullPath: '/challenges/$challengeId/submit'
      preLoaderRoute: typeof AppChallengesChallengeIdSubmitRouteImport
      parentRoute: typeof AppChallengesChallengeIdRouteRoute
    }
    '/_app/challenges/$challengeId/overview': {
      id: '/_app/challenges/$challengeId/overview'
      path: '/overview'
      fullPath: '/challenges/$challengeId/overview'
      preLoaderRoute: typeof AppChallengesChallengeIdOverviewRouteImport
      parentRoute: typeof AppChallengesChallengeIdRouteRoute
    }
    '/_app/challenges/$challengeId/leaderboard': {
      id: '/_app/challenges/$challengeId/leaderboard'
      path: '/leaderboard'
      fullPath: '/challenges/$challengeId/leaderboard'
      preLoaderRoute: typeof AppChallengesChallengeIdLeaderboardRouteImport
      parentRoute: typeof AppChallengesChallengeIdRouteRoute
    }
    '/_app/challenges/$challengeId/files': {
      id: '/_app/challenges/$challengeId/files'
      path: '/files'
      fullPath: '/challenges/$challengeId/files'
      preLoaderRoute: typeof AppChallengesChallengeIdFilesRouteImport
      parentRoute: typeof AppChallengesChallengeIdRouteRoute
    }
  }
}

interface AppChallengesChallengeIdRouteRouteChildren {
  AppChallengesChallengeIdFilesRoute: typeof AppChallengesChallengeIdFilesRoute
  AppChallengesChallengeIdLeaderboardRoute: typeof AppChallengesChallengeIdLeaderboardRoute
  AppChallengesChallengeIdOverviewRoute: typeof AppChallengesChallengeIdOverviewRoute
  AppChallengesChallengeIdSubmitRoute: typeof AppChallengesChallengeIdSubmitRoute
}

const AppChallengesChallengeIdRouteRouteChildren: AppChallengesChallengeIdRouteRouteChildren =
  {
    AppChallengesChallengeIdFilesRoute: AppChallengesChallengeIdFilesRoute,
    AppChallengesChallengeIdLeaderboardRoute:
      AppChallengesChallengeIdLeaderboardRoute,
    AppChallengesChallengeIdOverviewRoute:
      AppChallengesChallengeIdOverviewRoute,
    AppChallengesChallengeIdSubmitRoute: AppChallengesChallengeIdSubmitRoute,
  }

const AppChallengesChallengeIdRouteRouteWithChildren =
  AppChallengesChallengeIdRouteRoute._addFileChildren(
    AppChallengesChallengeIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppChallengesChallengeIdRouteRoute: typeof AppChallengesChallengeIdRouteRouteWithChildren
  AppChallengesIndexRoute: typeof AppChallengesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChallengesChallengeIdRouteRoute:
    AppChallengesChallengeIdRouteRouteWithChildren,
  AppChallengesIndexRoute: AppChallengesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminSubmissionsRouteChildren {
  AdminSubmissionsChar123submissionIdChar125_modalRoute: typeof AdminSubmissionsChar123submissionIdChar125_modalRoute
}

const AdminSubmissionsRouteChildren: AdminSubmissionsRouteChildren = {
  AdminSubmissionsChar123submissionIdChar125_modalRoute:
    AdminSubmissionsChar123submissionIdChar125_modalRoute,
}

const AdminSubmissionsRouteWithChildren =
  AdminSubmissionsRoute._addFileChildren(AdminSubmissionsRouteChildren)

interface AdminRouteRouteChildren {
  AdminSubmissionsRoute: typeof AdminSubmissionsRouteWithChildren
  AdminSubmissionsSubmissionIdRoute: typeof AdminSubmissionsSubmissionIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSubmissionsRoute: AdminSubmissionsRouteWithChildren,
  AdminSubmissionsSubmissionIdRoute: AdminSubmissionsSubmissionIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
